services:
  caddy:
    image: caddy:2.7.5-alpine
    restart: unless-stopped
    cpus: 1
    mem_limit: 512M
    pids_limit: 256
    ports:
      - "2112:2112"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./front:/var/www/simple:ro
    depends_on:
      - app
      - postgres
  app:
    build: .
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1
    pids_limit: 256
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=simple
      - POSTGRES_USER=simple
      - POSTGRES_DB=simple
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:rox
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
