# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"$\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"<\n\x12\x43reateTokenRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\x05token\x18\x02 \x01(\x0b\x32\x06.Token\",\n\x13\x43reateTokenResponse\x12\x15\n\x05token\x18\x01 \x01(\x0b\x32\x06.Token\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\":\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\'\n\x16InvalidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x19\n\x17InvalidateTokenResponse\"$\n\x11ListTokensRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x11ListTokenResponse\x12\x16\n\x06tokens\x18\x01 \x03(\x0b\x32\x06.Token2\x84\x02\n\x0cTokenService\x12\x38\n\x0b\x43reateToken\x12\x13.CreateTokenRequest\x1a\x14.CreateTokenResponse\x12>\n\rValidateToken\x12\x15.ValidateTokenRequest\x1a\x16.ValidateTokenResponse\x12\x44\n\x0fInvalidateToken\x12\x17.InvalidateTokenRequest\x1a\x18.InvalidateTokenResponse\x12\x34\n\nListTokens\x12\x12.ListTokensRequest\x1a\x12.ListTokenResponseB+\n\nauth.proto\xca\x02\tGRPC\\Auth\xe2\x02\x10GRPC\\GPBMetadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\nauth.proto\312\002\tGRPC\\Auth\342\002\020GRPC\\GPBMetadata'
  _globals['_TOKEN']._serialized_start=14
  _globals['_TOKEN']._serialized_end=50
  _globals['_CREATETOKENREQUEST']._serialized_start=52
  _globals['_CREATETOKENREQUEST']._serialized_end=112
  _globals['_CREATETOKENRESPONSE']._serialized_start=114
  _globals['_CREATETOKENRESPONSE']._serialized_end=158
  _globals['_VALIDATETOKENREQUEST']._serialized_start=160
  _globals['_VALIDATETOKENREQUEST']._serialized_end=197
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=199
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=257
  _globals['_INVALIDATETOKENREQUEST']._serialized_start=259
  _globals['_INVALIDATETOKENREQUEST']._serialized_end=298
  _globals['_INVALIDATETOKENRESPONSE']._serialized_start=300
  _globals['_INVALIDATETOKENRESPONSE']._serialized_end=325
  _globals['_LISTTOKENSREQUEST']._serialized_start=327
  _globals['_LISTTOKENSREQUEST']._serialized_end=363
  _globals['_LISTTOKENRESPONSE']._serialized_start=365
  _globals['_LISTTOKENRESPONSE']._serialized_end=408
  _globals['_TOKENSERVICE']._serialized_start=411
  _globals['_TOKENSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
