services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 7117:7117
    depends_on:
      - postgres
      - minio

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=numb
      - MINIO_ROOT_PASSWORD=6whMQ9fhHsaezmVr
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=numb
      - POSTGRES_USER=numb
      - POSTGRES_DB=numb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  minio_data:
  postgres:
